### ISSUE TITLE
browse doesn't always update the data

### ISSUE THREAD

**Issue by MLR-au** [MLR-au/pdsc-olac-visualisation#1]
I just found a bug. Having looked at my favourite language in Vanuatu, I then looked at Mangbutu in Congo, but the resources still listed Vanuatu and South Efate. It seems that it gets stuck with the earlier data and doesn't flush it before a new language is selected.

**Comment by nthieberger** [comment]
it seems that, if you search by country first then it doesn't forget that country in subsequent browses. But a browse done without a country search does not display the country before the language name (should it?)
