### ISSUE TITLE
One language is missing (that I have noticed) from the map

### ISSUE THREAD

**Issue by nthieberger** [MLR-au/pdsc-olac-visualisation#14]
Just happens to be the language I work on ! But why is this? The csv file has it ...
1753,erk,Efate, South,,-17.585,-17.83,168.159,168.594

**Comment by nthieberger** [comment]
extra comma after the name maybe?

**Comment by MLR-au** [comment]
Yep - exactly. There's not much I can do there. Can you fix the data - maybe change it to `South Efate`? If you can't change the name then another option is to change the delimiter from a comma to something else.

I also noticed in the languages file you sent that some have a missing field. Open the csv file in google sheets and you'll see that a lot of languages are missing the `retired` field so all the coord's are shifted left by one field. If you were able to fix these that would be very helpful.
