### ISSUE TITLE
add wave surfer

### ISSUE THREAD

**Issue by nthieberger** [MLR-au/pdsc-olac-visualisation#15]
Can you add this to the audio viewer? http://wavesurfer-js.org/ It should give a wave form that can be used to navigate the file. (I'm still hoping to get the more detailed image of the noise visualiser pre-generated and stored but that is taking time)
If it is too slow to load maybe it could be an option for the user to select, I'm not sure.

**Comment by nthieberger** [comment]
I noticed that wavesurfer also plays Elan files (our .eaf files) so that could be added to the player. http://wavesurfer-js.org/example/elan/

**Comment by MLR-au** [comment]
Moved to https://github.com/MLR-au/pdsc-collection-viewer/issues/2

**Comment by nthieberger** [comment]
oops, sorry!
