### ISSUE TITLE
Please change colours for accessibility

### ISSUE THREAD

**Issue by nthieberger** [MLR-au/pdsc-olac-visualisation#19]
http://safecolours.rigdenage.com/colourchoice.html

**Comment by MLR-au** [comment]
Google style guidelines - colours: https://material.google.com/style/color.html#color-color-palette

**Comment by MLR-au** [comment]
New version uploaded but leaving this ticket around until some feedback received.

**Comment by nthieberger** [comment]
<20  #212121
>20 #BDBDBD
>150 #FFEB3B
