### ISSUE TITLE
languages generating errors rather than links to OLAC

### ISSUE THREAD

**Issue by nthieberger** [MLR-au/pdsc-olac-visualisation#2]
These languages have a problem and generate the error shown in the attached screenshot:
Taveta (in Kilimanjaro park, Tanzania)
Lengola
Southeastern Dinka
Mangbutu
Mo'oda
Mbesa
Buwal
(actually this raises another issue, that these languages do not have URIs so I can't reference them, but I assume you can search for them?)

![screen shot 2016-01-04 at 11 22 51 am](https://cloud.githubusercontent.com/assets/611488/12081693/8c43e404-b2d5-11e5-80ad-8d8f387148c8.jpg)

**Comment by MLR-au** [comment]
This comes from not being able to get the data file for that language. There are a number of languages listed in the languages.csv for which there isn't a corresponding page at the language archives site. I'll need to check that it's not one of those or something else going wrong in the data generation code.

I think maybe I also need to make the error message a bit more appropriate: something like:

Unable to retrieve the information for that language or some such

**Comment by MLR-au** [comment]
ok - found the bug in my code!
