### ISSUE TITLE
confusing colour of icons

### ISSUE THREAD

**Issue by nthieberger** [MLR-au/pdsc-olac-visualisation#5]
The initial view of the map, with icons clumping languages under one needs to have white icons, or else use colours other than the traffic light colourss now used.

**Comment by MLR-au** [comment]
Ok - have gone with a nice shade of purple which stands out against the map but doesn't conflict with the pin colours. See attachment. If you don't like the colour have a look through http://www.flatuicolorpicker.com/all and provide some suggestions.
![screen shot 2016-01-09 at 10 54 59 am](https://cloud.githubusercontent.com/assets/2639995/12212543/ae253b5c-b6bf-11e5-9940-fdfee4e68b42.png)
