### ISSUE TITLE
The panel on the right does not work in Safari 

### ISSUE THREAD

**Issue by nthieberger** [MLR-au/pdsc-olac-visualisation#6]
any known prob that can be solved for this?

**Comment by MLR-au** [comment]
I've been totally unable to find out why this is happening. There are no errors in the console and nothing seems to be wrong. I haven't been able to find anything related by googling either.

It's little to no consolation but I've been reading that safari is not held in high regard in the web community; to some it's becoming what IE was in terms of standards compliance and keeping up to date with features. And this app is built using the latest and greatest AngularJS and Angular Material so it's definitely an oddity arising from safari working with one or both of those. 

If I figure out what's happening then I'll fix it but for now all i can say is don't use safari.

**Comment by MLR-au** [comment]
Seems to be working now.
