### ISSUE TITLE
can the map move to the selected language?

### ISSUE THREAD

**Issue by nthieberger** [MLR-au/pdsc-olac-visualisation#7]
it would be nice if the map would move along when selecting a language via the “plus” icon in the bottom right corner. (not sure whether that icon is the best choice to indicate the browse functionality, how about some way of indicting a search by country, maybe a small world map icon?)

**Comment by MLR-au** [comment]
Haven't tackled this yet but the plus icon is generally accepted to mean pressing this gets you more. That said, I'm happy to change it if you don't like it. Have a look at https://design.google.com/icons/ and let me know what you think is better (there isn't a world icon there unfortunately and even if there was it might be too small to make it in that little button).

**Comment by MLR-au** [comment]
ok - when coords are available the map zooms to the language and opens the popup.
